version: '3.9'
services:
  async:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: hix_test_async
    command: 'bundle exec sidekiq'
    volumes:
      - .:/app:cached
    depends_on:
      - kv
      - db
    env_file:
      - .env
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: 'bundle exec rails s --binding=0.0.0.0 --environment=${RAILS_ENV} --port=${PORT}'
    container_name: hix_test_app
    depends_on:
      - db
      - async
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - hix_test_bundle:/usr/local/bundle
      - hix_test_log:/app/log
      - hix_test_node_modules:/app/node_modules
      - hix_test_packs:/app/public/packs
      - hix_test_rails_cache:/app/tmp/cache
      - hix_test_tmp:/app/tmp
    ports:
      - '${EXPOSE_PORT_APP}:${PORT}'
  db:
    image: postgres:latest
    container_name: hix_test_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - hix_test_db:/var/lib/postgresql/data
  kv:
    image: redis:latest
    container_name: hix_test_kv
    env_file:
      - .env
    volumes:
      - hix_test_kv:/data
volumes:
  hix_test_bundle:
  hix_test_db: 
  hix_test_kv:
  hix_test_log:
  hix_test_node_modules:
  hix_test_packs:
  hix_test_rails_cache:
  hix_test_tmp:
